source "https://rubygems.org"

gem 'sinatra'
gem 'rack-contrib'
gem 'aws-record'
gem 'sinatra-validation'

group :test do
  gem 'rake'
  gem 'rspec'
  gem 'rack-test'
  gem 'simplecov'
  gem 'simplecov-console'
end
